# -*- coding: utf-8 -*-
"""QR code using python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bizqB3zESrXiCENO9ljPRYeQeP5vb0a1

#pyqrcode module is a QR code generator. The module automates most of the building process for creating QR codes. This module attempts to follow the QR code standard as closely as possible.

A QR Code is a scannable code used to store information. QR codes are used to redirect you to a specific page or to show you some information. You must have scanned QR codes once in your life when making payments.

QR codes have a variety of uses; from creating a payment gateway to showing you the food menu of a restaurant, a QR code is being used in several ways. Over the past five years, several businesses have started that are only based on creating QR codes for a business. So if you know how to create a QR code, it will be helpful for you in many ways.

So to create QR codes using the Python programming language, you first need to make sure that you have the **PyQRCode** and pypng modules installed in your Python virtual environment. You can easily install both of these modules by executing the commands mentioned below in your command prompt or terminal:

pip install PyQRCode
pip install pypng
After installing these modules, you can start writing a program to create a QR code using Python
"""

pip install pyqrcode

pip install pypng

import pyqrcode
import png

link="https://www.instagram.com/mrigankshigupta/?hl=en"

# Generate QR code
qr_code=pyqrcode.create(link)

# Create and save the png file
qr_code.png("mriganskhi.png",scale=6)

"""# The QR code generated by this Python program will be saved on the same directory where your Python file is."""

